#!/bin/bash
#
# Upgrade server and remove unused packages on Ubuntu 18.04.
# Usage
#   This script must be run as root (ex.: sudo sh ./[script_name]) and prior to
#   any server customization.
# Style Guide
#   https://google.github.io/styleguide/shellguide.html

# Functions
source ./logger.sh
source ./utils.sh

function main() {
  utils::set_exit_trap

  local waiting_time
  local -r MAX_WAIT_TIME=60

  #############################################################################

  logger::title "Start of $0"

  logger::info "This script: "
  logger::info "1) Upgrades all installed server packages"
  logger::info "2) Removes all packages that are no longer used"

  #############################################################################

  logger::action "Updating server package index files..."
  # Fix for issue-881.
  waiting_time=0
  while [[ $(pgrep apt) && ${waiting_time} -lt ${MAX_WAIT_TIME} ]]; do
    ((waiting_time++))
    logger::info "Waiting for other apt commands to finish: ${waiting_time} sec / ${MAX_WAIT_TIME} sec...";
    sleep 1;
  done;
  apt update

  logger::action "Upgrading all installed server packages to their latest version and apply available security patches..."
  apt upgrade -y

  logger::action "Removing server packages that are no longer needed."
  apt autoremove -y

  #############################################################################

  logger::title "End of $0"

  #############################################################################

  utils::unset_exit_trap
}

main "$@"
