#!/bin/bash
#
# Upgrade server and remove unused packages on Ubuntu 18.04.
# Usage
#   This script must be run as root (ex.: sudo sh ./[script_name]) and prior to
#   any server customization.
# Style Guide
#   https://google.github.io/styleguide/shellguide.html

# Functions
source ./logger.sh
source ./utils.sh

function main() {
  utils::set_exit_trap

  #############################################################################

  logger::title "Start of $0"

  logger::info "This script: "
  logger::info "1) Upgrades all installed server packages"
  logger::info "2) Removes all packages that are no longer used"

  #############################################################################

  logger::action "Updating server package index files..."
  apt update

  logger::action "Upgrading all installed server packages to their latest version and apply available security patches..."
  apt upgrade -y

  logger::action "Removing server packages that are no longer needed."
  apt autoremove -y

  #############################################################################

  logger::title "End of $0"

  #############################################################################

  utils::unset_exit_trap
}

main "$@"
